### ISSUE TITLE
bug: Newest update broke packet capture

### ISSUE THREAD

**Issue by VitalSuit** [ffxiv-teamcraft/ffxiv-teamcraft#1257] opened 2019-11-28 21:17 UTC
As the title says, the newest update broke packet capture for inventory.

It'll get a read on my inventory but it will not update immediately like it used to, I have to change zones for the inventory to be updated.

Previously my inventory (and my list on the app) would update as stuff was gathered/crafted but now it will snapshot what it saw as I entered a new zone, and won't update until I teleport to a new zone.

So for example let's say I have 100 of one item. The app will say "inventory 100", let's say I just gathered an extra 50. The app will still say "inventory 100" until I teleport to a new zone which it will then update to "inventory 150".

Sorry if this isn't very helpful, I'm new to reporting bugs on practically anything

**Comment by Supamiu** [comment] 2019-11-28 23:28
Duplicate of #1250

**Closed by Supamiu** 2019-11-28 23:28 UTC
