### ISSUE TITLE
Bug: BSOD's and Javascript errors

### ISSUE THREAD

**Issue by Edrialyse** [ffxiv-teamcraft/ffxiv-teamcraft#1563] opened 2020-07-26 16:13 UTC
## I'm submitting a...
* (_) Bug report *- please add **bug:** before the title*

I don't understand the pre filled requests of what its all asking for me to put in because i don't understand coding in the slightest. So I'm going to put what I know is happening. I'm on windows 10 64 bit. I installed Teamcraft up until 7.2.10 and it always worked fine. After 7.2.10 and so far continuing with 7.2.11, the first thing that pops up when trying to open after the install is a humongous javascript error.

Uncaught Exception:
Error: listen EADDRINUSE: address already in use ::::13346
at Server.Setup.ListenHandle [as _ listen2] (net.js 1228:14)
at listenInCluster (net.js: 1276:12)
at Server.listen (net.js: 1364:7)
at MachinaFFXIV.start
(C:\Users\MYNAME\AppData\Local\ffxivv-teamcraft\app-7.2.11\resources\app.asar\node_m.....:26)
at
C:\Users\MYNAME\AppData\Local\ffxiv-teamcraft\app-7.2.11\resources\app.asar\desktop\...:15
at processTicksAndRejections (internal/process/task_queues.js:85:5)

it did this before with 7.2.10 and while attempting to play FFXIV caused a DPC_WATCHDOG_VIOLATION blue screen several times in a row. I isolated it to the Teamcraft desktop app after a final reboot and attempting to play my game -without- using the teamcraft desktop app at all. I had hoped this new version would solve the problem that again, never had prior to 7.2.10 and 7.2.11. I never changed any windows settings, firewall settings, nothing and everything had run perfectly fine. Now, I'm terrified to use anything but the website version for fear of tanking my pc. i dont have any javascript blockers that I know of because if I did the previous versions would have had issues like this as well. I even uninstalled completely and reinstalled several times to see if it was an installation issue of some kind.

![Javascript error](https://user-images.githubusercontent.com/68449210/88483944-fe8fe380-cf1f-11ea-88e4-aa00f1d53276.png)

**Comment by Supamiu** [comment] 2020-07-26 18:39
Hello, your problem consists of two separate errors:

The EADDRINUSE one, this one means that Teamcraft didn't stop properly and is probably still running, starting another instance will produce this error.

The BSOD one, this one is due to a corrupted driver on your PC or an issue with one of your PC's parts, it has nothing to do with Teamcraft, but Teamcraft is maybe provoking it by using the affected part in such a way that it triggers the error.

As I'm not able to reproduce this or fix anything, I'm going to close this as cannot reproduce, but if you need more help, I'll be happy to reply with more details if needed.

**Closed by Supamiu** 2020-07-26 18:39 UTC
