### ISSUE TITLE
Feat:  Submit links and items usable even on unfinished items in database

### ISSUE THREAD

**Issue by kmacdon72** [ffxiv-teamcraft/ffxiv-teamcraft#2070] opened 2021-11-26 17:27 UTC
If you go to Quest:  Onions of Life Bestowing it is one if the unfinished objected.  Not having all of the NPCs or objects involved.  But there is also no button for me to submit like the current Garland link.  NPC involved in the quest.  Thinks like that.  People might be willing to help with info gathering but not very good with tech.  if you give them a quick button to add info to the item.  they may be more willing to give information.  

I have resorted to just adding in a comment if I have had no other way but it does not get information to you the developer to add to the database if needed.

Just a thought.

**Comment by Supamiu** [comment] 2021-11-27 21:40
I'm sorry but I don't understand what you are suggesting here, maybe you mean something like the allagan-reports system which is a button right under an item's name that's labelled "add data sources for this item".

Aside from that, please use the template for feature requests, it's here to make sure the the issue is udnerstandable for me.

Last but not least, not everything that's listed on GarlandTools (I assume that's what you meant by Garland link) can be done on Teamcraft for now, and I won't implement NPC <=> Quest links maintaining by hand because there's way too much content for that and nobody will ever maintain it, not to mention links that will be removed with future updates.

I'm closing this because I can't understand what you mean and I can't accept just a sentence out of the box with just no template usage at all.

**Comment by Supamiu** [comment] 2021-11-27 21:41
I'm sorry but I don't understand what you are suggesting here, maybe you mean something like the allagan-reports system which is a button right under an item's name that's labelled "add data sources for this item".

Aside from that, please use the template for feature requests, it's here to make sure the the issue is udnerstandable for me.

Last but not least, not everything that's listed on GarlandTools (I assume that's what you meant by Garland link) can be done on Teamcraft for now, and I won't implement NPC <=> Quest links maintaining by hand because there's way too much content for that and nobody will ever maintain it, not to mention links that will be removed with future updates.

I'm closing this because I can't understand what you mean and I can't accept just a sentence out of the box with just no template usage at all.

**Closed by Supamiu** 2021-11-27 21:40 UTC
