### ISSUE TITLE
Bug: ECONNRESET at TLSWrap.onStreamRead

### ISSUE THREAD

**Issue by jianke333** [ffxiv-teamcraft/ffxiv-teamcraft#2272] opened 2022-05-19 11:23 UTC
**Describe the bug**
pop up 1
A JavaScript error occured in the main process. 
Uncaught Exception: Error: read ECONNRESET at TLSWrap.onStreamRead (node:internal/stream_base_commons:220:20)

pop up 2
A JavaScript error occured in the main process. 
Uncaught Exception: Error: connect ETIMEDOUT 104.224.45.246:443
at TCPConnectWrap.afterConnect[as oncomplete] (node:net:1161:16)

**To Reproduce**

Open Teamcraft v9.6.6
Error pop up sometime 1 sometime 2.

Go to "Settings" -> "Desktop" -> "Packet Capture"
Check / Uncheck "enable packet capture"
Error pop up sometime 1 sometime 2.

Go to "Profile" -> ”Jobs“ -> "Autofill stats using packet capture".
Open UI normally and nothing happened after I change jobs.

**Expected behavior**
No error pop up

**Screenshots**
Same with 'Describe the bug'

**Desktop (please complete the following information):**
 - OS: Windows 10 21H2(19044.1706)
 - language: ZH
 - Version TC 9.6.6

**Additional context**

**Comment by Supamiu** [comment] 2022-05-19 12:37
Duplicate of #2262, will be fixed with 9.6.7

**Closed by Supamiu** 2022-05-19 12:37 UTC
