### ISSUE TITLE
bug: listen EADDRINUSE: address already in use

### ISSUE THREAD

**Issue by BlankShrimp** [ffxiv-teamcraft/ffxiv-teamcraft#2289] opened 2022-06-29 17:47 UTC
*please start the issue name with "bug: ", example: "bug: cannot register on ios"*

**Describe the bug**
Launch desktop app failed with following error:
listen EADDRINUSE: address already in use 127.0.0.1:13346

**To Reproduce**
1. Install latest version
2. Launch it (or wait installation to launch automatically, PC reboot also tried)
3. Error: listen EADDRINUSE: address already in use, localhost port 13346

**Expected behavior**
No error pops.

**Screenshots**
Error1:
![image](https://user-images.githubusercontent.com/35521976/176500559-fc633a37-251e-47db-81a8-206722934e86.png)
When error1 is dismissed, another error pops:
![image](https://user-images.githubusercontent.com/35521976/176499633-f1f04664-8fab-488c-85f4-0dda3eaaafe4.png)
confirming port usage:
![image](https://user-images.githubusercontent.com/35521976/176501834-7ba4fe10-cdbe-49b3-af81-c40dfafd849b.png)
all processes were created together by single click:
![image](https://user-images.githubusercontent.com/35521976/176500670-a6f7b8d9-44c8-4d92-a3d8-e4fb4f3d57e6.png)

**Desktop (please complete the following information):**
 - OS: Windows 11 22H2
 - Browser [e.g. chrome, safari, desktop app]
 - Version v9.6.12

**Additional context**
1. Tried command netstat -ano |findstr "13346" to locate the port usage, noticed that the port was obssesed by one of the four Teamcraft.exe processes (as shown above). These four processes were created together, and in the pictures' case, pid 3000 was the deamon.
2. Reinstallation tried.
3. Run as admin tried.
4. Reboot computer tried.
5. Kill all teamcraft.exe tried.

**Comment by Supamiu** [comment] 2022-06-30 08:18
This is due to a process not killed properly, probably due to the pipe being destroyed, solutions are being worked on to better handle errors and kill the process properly.

After a reboot, this should be fixed and if it's not, it's due to something on your computer listening to localhost:13346, and thus using the port.

Teamcraft creates multiple processes for multiple uses, and one of them needs to listen on localhost:13346 to receive the packet traffic from the packet capture system.

I'm closing this as cannot reproduce, but I know part of it is caused by the error handling being missing for some specific errors, resulting in the listener not being closed properly, and this is being worked on. Your error looks like something on your PC listening to this port tho, because restarting your computer should fix the bug and if it didn't, then it's definitely not TC's fault.

**Closed by Supamiu** 2022-06-30 08:18 UTC
