### ISSUE TITLE
Bug - Desktop App sign in via google fails

### ISSUE THREAD

**Issue by DArrigoni** [ffxiv-teamcraft/ffxiv-teamcraft#1269] opened 2019-12-01 20:12 UTC
## I'm submitting a...
* (X) Bug report 
* (_) Feature request 
* (_) Support request

## Environment
Desktop App

## Current behavior
Attempting to Login via Google gives an error:

"Couldn't sign you in
You are trying to sign in from a browser or app that doesn't allow us to keep your account secure."

Screenshot: https://gyazo.com/e6bd235d9502cfa99e2427c2d578a3cf

## Expected behavior

Application logs me in and loads my stuff

## Steps to reproduce
1. From Desktop app, click "Anonymous" > "Login"
2. Click "Log In with Google"
3. Enter credentials for a verified Google based account

**Comment by Supamiu** [comment] 2019-12-02 16:42
Hey, thank you for youre report,

Your windows must have something different, because I am not able to reproduce this on a dev instance nor with the production build. Do you know what could make your PC different in any ways?

**Comment by graldur** [comment] 2019-12-03 00:10
I also have the same issue.  I am running Windows 10 Pro version 1909, build 18363.476.  I also have 2 factor authentication enabled on my Google account.

**Comment by Supamiu** [comment] 2019-12-07 09:29
Was this fixed by 6.3.3?

**Comment by graldur** [comment] 2019-12-07 17:51
No.

**Comment by datsepp** [comment] 2019-12-15 00:18
Can confirm.

![image](https://user-images.githubusercontent.com/34925579/70856256-a3e9d000-1ed8-11ea-8603-f2c6cc781e90.png)

**Comment by Dormanil** [comment] 2019-12-18 02:36
I am going to assume that I have to enable this setting to login on the desktop app?
![image](https://user-images.githubusercontent.com/6816490/71051059-4e672a80-2147-11ea-8dff-3630e970d15d.png)

"This Setting" can be found under [your Google account's security settings.](https://myaccount.google.com/security)

**Comment by chernobog** [comment] 2020-01-09 16:22
I'm also using 2FA with a Google account to log in, and having the same issue preventing logging into the desktop app. I've found a kind of work around. 
1. Go to your profile on the website: https://ffxivteamcraft.com/profile
2. Go to the Account section
3. Click Reset Password. Follow the instructions to complete a password reset.
4. Use your email address and new password to log into the desktop app.

Obviously, you're no longer using Google OAuth to login, but at least you can use the desktop app.

**Comment by FaeyUmbrea** [comment] 2020-08-12 23:17
The bug reappeared in the current release for me, reopening the issue might be necessary.

**Comment by Gentle** [comment] 2020-10-04 12:49
it reappeared again, if I can do anything to help debug I'd be willing to do so

**Comment by Supamiu** [comment] 2020-10-04 14:20
Hm, are you getting the exact same error message? I fixed this a couple of months ago by spoofing the User Agent.

**Comment by Supamiu** [comment] 2020-10-17 08:52
I'm closing this because of Inactivity, maybe it was just a small hiccup

**Closed by Supamiu** 2020-10-17 08:52 UTC
Labels: app: windows, difficulty: hard
