### ISSUE TITLE
bug: Skills show as usable on first action when crafter level is not high enough.

### ISSUE THREAD

**Issue by Caraxi** [ffxiv-teamcraft/ffxiv-teamcraft#1456] opened 2020-03-12 03:04 UTC
*please start the issue name with "bug: ", example: "bug: cannot register on ios"*

**Describe the bug**
When starting a new rotation with a low level crafter all actions show as available for the first action regardless of the defined crafter level.

**To Reproduce**
1. Go to 'Simulator'
2. Set level to 1
3. Clear rotation completely
4. All actions will show as available until an action is added to the rotation.

**Expected behavior**
Actions above the crafter's level should be displayed as grayed out as they do when actions are in the rotation.

**Screenshots**
![Screenshot](https://i.imgur.com/psrBV3J.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Firefox
 - Version: Firefox 73.0.1, Teamcraft 7.0.14

**Additional context**

**Comment by Supamiu** [comment] 2020-03-12 07:03
This is not really a bug as it's intended behavior, but I get why you're reporting that.

Basically, as of today, the simulation is the pat of the logic telling us if there's any errors, the issue is that with no actions, there's no simulation. So you can input an action, then the simulation will turn into error state, showing that you don't have required stats.

This could probably be changed using a first level of check being done inside the simulator component itself, not sure on the costs vs benefits on this one tho.

This was changed in https://github.com/ffxiv-teamcraft/ffxiv-teamcraft/commit/af6db48

**Comment by Supamiu** [comment] 2020-05-11 13:51
I'm closing this as the cost is way too high compared to the benefits, as it shows an error after you entered one action, I'd say it's "ok".

**Closed by Supamiu** 2020-05-11 13:51 UTC
Labels: bug, difficulty: hard
