### ISSUE TITLE
bug: Reordering actions in crafting simulator has unexpected results when icons take up more than 1 row

### ISSUE THREAD

**Issue by Trainerredstone7** [ffxiv-teamcraft/ffxiv-teamcraft#2582] opened 2023-04-09 21:21 UTC
Description: When sufficiently many actions have been added to a simulated craft to cause the action icons to wrap around to a second row, clicking and dragging actions does not rearrange them properly. Instead, actions that were not dragged will move to random spots instead.

**To Reproduce**
1: Open a recipe in the crafting simulator (for example, Grade 7 Tincture of Mind).
2: Add actions to the craft until they wrap around to the second row.
3: Drag an action to a different spot in the rotation (between two other actions), then drop the action. The dropped action will not be placed between the two other actions, but will return to its original spot. Instead, a different action in the rotation will be moved to a seemingly unrelated spot.

Here is a rotation (in crafting optimizer format) that shows this issue: ["muscleMemory","manipulation","veneration","wasteNot2","groundwork","groundwork","carefulSynthesis","innovation","preparatoryTouch","preparatoryTouch","preparatoryTouch","preparatoryTouch","innovation","basicTouch","standardTouch","trainedFinesse","trainedFinesse","tricksOfTheTrade","tricksOfTheTrade","tricksOfTheTrade","tricksOfTheTrade","tricksOfTheTrade","tricksOfTheTrade","innovation","trainedFinesse","tricksOfTheTrade","greatStrides","byregotsBlessing","delicateSynthesis"]

If the rotation does not wrap due to larger screen size, add more tricks of the trade in the middle until it does. Try moving the position of Great Strides to observe the bug.

**Expected behavior**
When dragging and dropping an action icon within a rotation, it should be inserted between the two actions it is dropped between.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser desktop app
 - Version 10.4.8 of desktop app
 - 15.6" screen

**Comment by Supamiu** [comment] 2023-04-10 14:46
duplicate of #1742

**Closed by Supamiu** 2023-04-10 14:46 UTC
Labels: duplicate
