### ISSUE TITLE
Bug: Creating quick list does not immediately open list

### ISSUE THREAD

**Issue by DingFandango** [ffxiv-teamcraft/ffxiv-teamcraft#1247] opened 2019-11-25 19:29 UTC
**Describe the bug**
Creating a quick list from searches or gc supplies does not automatically send you to the recipe list as it used to.

**To Reproduce**
1. Go to search
2. Look up any recipe
3. Create a quick list

                Or
 
1. Go to Grand Company Supplies
2. Fill out the form
3. Create quick list

**Expected behavior**
Before this bug started happening, Teamcraft would automatically bring you to the quick list you just created. 

**Desktop (please complete the following information):**
Windows 10
Version 6.2.7

**Comment by Supamiu** [comment] 2019-11-26 07:42
Hi, thank you for the report, can you add console output please?

**Comment by DingFandango** [comment] 2019-11-26 17:04
How do I add console output?

**Comment by Supamiu** [comment] 2019-11-26 21:31
Go to the discord server and type !!coneols in the chat, then add the output here either as file upload or screenshot if there's some errors.

**Comment by Supamiu** [comment] 2019-12-07 09:34
I'm closing this as I cannot reproduce.

**Closed by Supamiu** 2019-12-07 09:34 UTC
Labels: bug, difficulty: medium
