### ISSUE TITLE
A JavaScript error occured in the main process

### ISSUE THREAD

**Issue by ShiTsubasa** [ffxiv-teamcraft/ffxiv-teamcraft#2760] opened 2024-02-04 15:29 UTC
Upon the update to 11.0.22, started recieving the error in title.

**Describe the bug**
Launching ffxiv-teamcraft has a popup error.

**To Reproduce**
1. Happens every time I try to launch TC

**Screenshots**
![image](https://github.com/ffxiv-teamcraft/ffxiv-teamcraft/assets/158834818/b2c1b390-b686-4c27-a665-2359c654dbe3)

**Desktop (please complete the following information):**
 - OS: Windows 10 Home v22H2
 - App v11.0.22

**Additional context**
Error happened before I saw the notification to update.  Gamewise, I was in Eureka: Pagos preparing a Copycat Cassie spawn.

**Comment by Supamiu** [comment] 2024-02-04 15:30
Duplicate of #2759

**Closed by Supamiu** 2024-02-04 15:30 UTC
